[package]
name = "uni-verify"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
uni-ir = { path = "../uni-ir" }
uni-evidence = { path = "../uni-evidence" }
toml.workspace = true
chrono.workspace = true
wait-timeout.workspace = true
jsonwebtoken.workspace = true
